export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

// TODO: add the body again
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
    </html>
  );
}
